name: Deploy S3

on:
  push:


permissions:
  contents: read

concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}  
  cancel-in-progress: true

# env:
#   AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    name: deploy s3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Display deployment information
        run: |
          echo "=========================================="
          echo "Create S3 bucket"
          echo "=========================================="
          echo "Triggered at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          echo "Workflow ref: ${{ github.ref }}"
          echo "Workflow ref name: ${{ github.ref_name }}"
          echo "Triggered by: ${{ github.actor }}"
          echo "Event name: ${{ github.event_name }}"
          echo "=========================================="
          
      # - name: deploy s3
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   run: |
      #     aws --version
      #     aws sts get-caller-identity
      #     aws s3api list-buckets
      #     echo " Creating S3 "
      #     aws s3api create-bucket --bucket amzn-${{ env.CLOUD_IDENTIFIER }}-s3-github-bucket --region eu-central-1 --create-bucket-configuration LocationConstraint=eu-central-1
      #     aws s3api delete-public-access-block --bucket amzn-${{ env.CLOUD_IDENTIFIER }}-s3-github-bucket
      #     aws s3api put-bucket-policy --bucket amzn-${{ env.CLOUD_IDENTIFIER }}-s3-github-bucket --policy file://policy.json
      #     aws s3 website s3://amzn-${{ env.CLOUD_IDENTIFIER }}-s3-github-bucket --index-document index.html --error-document error.html
      #     aws s3 sync ./public s3://amzn-${{ env.CLOUD_IDENTIFIER }}-s3-github-bucket

      # - name: destroy s3
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   run: |
      #     aws --version
      #     aws sts get-caller-identity
      #     aws s3api list-buckets
      #     echo " Removing S3 "
      #     aws s3 rm s3://amzn-${{ env.CLOUD_IDENTIFIER }}-s3-github-bucket --recursive
      #     aws s3api delete-bucket --bucket amzn-${{ env.CLOUD_IDENTIFIER }}-s3-github-bucket
